search_api_field.plugin.filter.node_entity_autocomplete:
  type: joinup_search_filter_plugin_entity_autocomplete
  label: 'Node entity label autocomplete'

search_api_field.plugin.filter.rdf_entity_autocomplete:
  type: joinup_search_filter_plugin_entity_autocomplete
  label: 'Rdf entity label autocomplete'

joinup_search_filter_plugin_entity_autocomplete:
  type: search_api_field_plugin_filter
  mapping:
    target_id:
      type: string
      label: 'Target id'
