version: '2'
services:
  web:
    build:
      context: ./resources/docker/web
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html # Non Mac users.
      # - nfsmount:/var/www/html # Mac Users with the nfsmount volume.
    environment:
      XDEBUG_CONFIG: "remote_enable=1 xdebug.remote_connect_back=1 remote_host=10.254.254.254 remote_port=9000 idekey=PHPSTORM remote_autostart=0"
      DOCUMENT_ROOT: "/var/www/html/web"
      PHP_XDEBUG_ENABLED: "1"
      PHP_IDE_CONFIG: "serverName=Docker"
      PHP_SENDMAIL_PATH: "/usr/sbin/sendmail -t -i -S mailhog:1025"
      # For Xdebug setup, run this command in the terminal:
      # For Mac users: sudo ifconfig en0 alias 10.254.254.254 255.255.255.0
      # For Linux users: sudo ip addr add 10.254.254.254/32 dev lo label lo:1

  # This will compile the CSS once when docker-compose is started.
  sass:
    image: pablofelix/sass
    volumes:
      - $PWD:/app/
    entrypoint:
      - watch
      - -t compressed
      - /app/web/themes/joinup/prototype/sass/app.sass
      - /app/web/themes/joinup/css/style.min.css

  mysql:
    image: percona/percona-server:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: 'joinup'
      MYSQL_PASSWORD: 'joinup'
      MYSQL_DATABASE: 'joinup'
    volumes:
      - mysql:/var/lib/mysql

  virtuoso:
    image: tenforce/virtuoso
    environment:
      - SPARQL_UPDATE=true
      - DBA_PASSWORD=dba
    ports:
      - "8890:8890"

  mail:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  selenium:
    image: selenium/standalone-chrome-debug:3.11
    ports:
      - "5900:5900"
    expose:
      - "4440"
    volumes:
      # Needed due to chrome having issues with memory usage. Firefox does not face this issue.
      # @see: https://github.com/elgalu/docker-selenium/issues/20
      - "/dev/shm:/dev/shm"

  solr_published:
    build:
      context: ./resources/docker/solr
    ports:
     - "8982:8983"
    volumes:
      # - data:/opt/solr/server/solr/mycores
      - solr_published:/opt/solr/server/solr
    entrypoint:
     - docker-entrypoint.sh
     - solr-precreate
     - drupal_published
     - "/opt/docker-solr/configsets/drupal"

  solr_unpublished:
    build:
      context: ./resources/docker/solr
    ports:
     - "8983:8983"
    volumes:
      # - data:/opt/solr/server/solr/mycores
      - solr_unpublished:/opt/solr/server/solr
    entrypoint:
     - docker-entrypoint.sh
     - solr-precreate
     - drupal_unpublished
     - "/opt/docker-solr/configsets/drupal"

volumes:
  mysql:
  solr_published:
  solr_unpublished:

#### Mac users: uncomment the "volumes" key to enable the NFS file sharing. You can find more information about Docker for Mac here: https://github.com/openeuropa/openeuropa/blob/master/docs/starting/tooling.md#using-docker-on-macos

#volumes:
#  nfsmount:
#    driver: local
#    driver_opts:
#      type: nfs
#      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
#      device: ":${PWD}/"

#### End Mac users.
