version: '2'
services:
  mysql:
    volumes:
      - "./tmp/dump.sql:/docker-entrypoint-initdb.d/dump.sql"

  virtuoso:
    volumes:
      - "./tmp/dump-virtuoso:/data/backupToRestore"
    environment:
      - BACKUP_PREFIX=JOINUP_FULL_DUMP_

