subscription_configuration.*:
  type: config_entity
  label: 'Subscription configuration config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    uid:
      type: string
      label: 'User ID'
    group_types:
      type: text
      label: 'Group types'
    frequency:
      type: string
      label: 'frequency'

subscription_configuration.settings:
  type: config_object
    label: 'Joinup subscription settings'
    mapping:
      default_group_types:
        type: sequence
        label: 'The groups that the user receives notifications'
        sequence:
          type: string
          label: 'The machine name of the content.'
      frequency:
        type: string
        label: 'The frequency of the notifications'