# Config schema for Tallinn module.

tallinn.settings:
  type: config_object
  label: 'Tallinn configuration'
  mapping:
    dashboard:
      type: mapping
      label: Dashboard
      mapping:
        access_type:
          type: string
          label: 'Type of access'
