joinup_document.settings:
  type: config_object
  label: 'Document workflow permission settings'
  mapping:
    transitions:
      type: sequence
      label: 'Transitions allowed'
      workflow_id:
        type: sequence
        label: 'Workflow id'
        sequence:
          type: sequence
          label: 'Target state'
          sequence:
            type: sequence
            label: 'Source state'
            sequence:
              type: string
              label: 'Roles'
