collection.settings:
  type: config_object
  label: 'Collection workflow permission settings'
  mapping:
    transitions:
      type: sequence
      label: 'Allowed transitions'
      sequence:
        type: sequence
        label: 'Target state'
        sequence:
          type: sequence
          label: 'Source state'
          sequence:
            type: string
            label: 'Role'

# Schema for the og menu.
block.settings.collection_menu_block:*:
  type: block_settings
  label: 'Og menu block settings'
  mapping:
    level:
      type: integer
      label: 'Starting level'
    depth:
      type: integer
      label: 'Maximum number of levels'

# Schema for 'last_update_timestamp' formatter settings.
field.formatter.settings.last_update_timestamp:
  type: field.formatter.settings.timestamp
  label: 'Joinup Last Update display format settings'
  mapping:
    tooltip_format:
      type: string
      label: 'Tooltip date format'
    tooltip_format_custom:
      type: string
      label: 'Tooltip custom date format'
    timeago_settings:
      type: ignore
      label: 'Timeago plugin settings'
