joinup_notification.settings:
  type: config_object
  label: 'Notification settings'
  mapping:
    transition_notifications:
      type: sequence
      label: 'Workflow group'
      sequence:
        type: sequence
        label: 'Transition'
        sequence:
          type: sequence
          label: 'Roles'
          sequence:
            type: string
            label: 'Message ID'
    delete_notifications:
      type: sequence
      label: 'Entity type'
      sequence:
        type: sequence
        label: 'Bundle'
        sequence:
          type: sequence
          label: 'Roles'
          sequence:
            type: string
            label: 'Message ID'
